
:: 颜色定义
::"BLUE=%ESC%[94m"
::"GREEN=%ESC%[92m"
::"YELLOW=%ESC%[93m"
::"ORANGE=%ESC%[33m"
::"ORANGEPRO=%ESC%[38;5;208m"
::"PINK=%ESC%[95m"
::"RED=%ESC%[91m"
::"CYAN=%ESC%[96m"
::"WHITE=%ESC%[97m"
::"RESET=%ESC%[0m"
ECHO.%YELLOW%致谢名单[排名不分先后，标签不表贡献]
ECHO.════════════════════════════════
ECHO.%RED%[开发者%ORANGEPRO%辅助]%ORANOE%小白人%GREEN%QF%CYAN%ZM%BLUE%（不知道%PINK%取什么名字好）%RESET%
ECHO.%WHITE%[QQ]纯黑%RESET%
ECHO.%WHITE%[工具箱及其团队]NEW CRACK%RESET%
ECHO.%WHITE%[工具]小天才全系列root工具离线版%RESET%
ECHO.%YELLOW%════════════════════════════════%RESET%